
server:
  port: 8082
  
spring:               
  application:
    name: rating-service   
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka    

      
      
